[versions]
agp = "8.7.3"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
mapsVersion = "19.0.0"
retrofitVersion="2.11.0"
fragmentKtx = "1.8.5"
converterVersion = "2.11.0"
ktor = "3.0.3"
javaLifeCycle="$lifecycle_version"
lifecycleRuntimeKtx = "2.4.0-alpha03"
lifeCycleComposeVer = "2.8.5"
liveDataVersion="2.8.7"
kotlinSerialization = "1.8.0"
kotlinSerialization1 = "2.1.10"
kotlinJvm = "2.1.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
retrofit-converter = {group = "com.squareup.retrofit2",name="converter-gson",version.ref="converterVersion"}
google-maps = {group="com.google.android.gms",name="play-services-maps",version.ref="mapsVersion"}
retrofit = {group="com.squareup.retrofit2",name="retrofit",version.ref="retrofitVersion"}
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-compose = {group="androidx.lifecycle",name="lifecycle-runtime-compose",version.ref="lifeCycleComposeVer"}
androidx-lifecycle-java = {group="androidx.lifecycle",name="lifecycle-common-java8",version.ref="javaLifeCycle"}
androidx-lifecycle-livedata = {group="androidx.lifecycle",name="lifecycle-livedata-ktx",version.ref="liveDataVersion"}
androidx-kotlin-serialization = {group="org.jetbrains.kotlinx",name="kotlinx-serialization-json",version.ref="kotlinSerialization"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
picasso = { group = "com.squareup.picasso", name = "picasso", version = "2.8" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization1"}
